name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build project
        run: ./gradlew assembleRelease
        env:
          VERSION: ${{ github.ref }}
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          commit-ish: HEAD
      - run: |
          assets=$(find . -name "*release.apk" | while read -r asset ; do echo "-a $asset" ; done)
          hub release create ${assets} -m "${{steps.tagger.outputs.tag}}" "${{steps.tagger.outputs.tag}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{steps.tagger.outputs.tag}}
